[build-system]
requires = ["setuptools", "wheel", "setuptools_scm"]
build-backend = 'setuptools.build_meta'

# This project is using setuptools see setup.cfg to add new depdenencies and update metadata
